import { db } from './firebase-config.js';
import { collection, addDoc, onSnapshot, deleteDoc, doc, query, orderBy } from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";

document.addEventListener('DOMContentLoaded', () => {
    // DOM Elements
    const dateInput = document.getElementById('entry-date');
    const mealTimeBtns = document.querySelectorAll('#meal-time-group .toggle-btn');
    const mealTypeBtns = document.querySelectorAll('#meal-type-group .toggle-btn');
    const addEntryBtn = document.getElementById('add-entry-btn');
    const monthSelect = document.getElementById('month-select');
    const totalDaysEl = document.getElementById('total-days');
    const totalMealsEl = document.getElementById('total-meals');
    const totalCostEl = document.getElementById('total-cost');
    const historyList = document.getElementById('history-list');
    const currentDateDisplay = document.getElementById('current-date-display');

    // State
    let entries = [];
    let currentSelection = {
        mealTime: 'lunch',
        mealType: 'veg',
        price: 70
    };

    // Set default date to today
    const today = new Date().toISOString().split('T')[0];
    dateInput.value = today;

    // Format "Today" display
    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    currentDateDisplay.textContent = new Date().toLocaleDateString('en-US', options);

    // Initialize
    initMonthSelector();
    // No manual render(), listener handles it

    // Real-time Listener
    const q = query(collection(db, "entries"), orderBy("date", "desc"));
    const unsubscribe = onSnapshot(q, (snapshot) => {
        entries = snapshot.docs.map(doc => ({
            id: doc.id,
            ...doc.data()
        }));
        render();
    }, (error) => {
        console.error("Error getting documents: ", error);
        // Fallback or error message could go here
        historyList.innerHTML = `<div class="empty-state" style="color:var(--danger-color)">Error connecting to database. check config.</div>`;
    });

    // Event Listeners
    mealTimeBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            mealTimeBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            currentSelection.mealTime = btn.dataset.value;
        });
    });

    mealTypeBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            mealTypeBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            currentSelection.mealType = btn.dataset.value;
            currentSelection.price = currentSelection.mealType === 'veg' ? 70 : 80;
        });
    });

    addEntryBtn.addEventListener('click', addEntry);
    monthSelect.addEventListener('change', render);

    // Functions
    async function addEntry() {
        const date = dateInput.value;
        if (!date) {
            alert('Please select a date');
            return;
        }

        const newEntry = {
            date: date, // ID is auto-generated by Firestore
            mealTime: currentSelection.mealTime,
            mealType: currentSelection.mealType,
            price: currentSelection.price,
            timestamp: Date.now() // Useful for sorting stability if dates are same
        };

        try {
            addEntryBtn.textContent = "Adding...";
            await addDoc(collection(db, "entries"), newEntry);

            // Visual feedback
            addEntryBtn.textContent = "Added!";
            setTimeout(() => {
                addEntryBtn.textContent = "Add Entry";
            }, 1000);
        } catch (e) {
            console.error("Error adding document: ", e);
            alert("Error adding entry. Check your internet connection.");
            addEntryBtn.textContent = "Add Entry";
        }
    }

    async function deleteEntry(id) {
        if (confirm('Are you sure you want to delete this entry?')) {
            try {
                await deleteDoc(doc(db, "entries", id));
            } catch (e) {
                console.error("Error deleting document: ", e);
                alert("Error deleting entry.");
            }
        }
    }

    function initMonthSelector() {
        const monthNames = ["January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"];

        const currentconfig = new Date();
        const currentMonth = currentconfig.getMonth();
        const currentYear = currentconfig.getFullYear();

        // Populate with current month and previous 11 months
        for (let i = 0; i < 12; i++) {
            const d = new Date(currentYear, currentMonth - i, 1);
            const monthValue = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
            const monthLabel = `${monthNames[d.getMonth()]} ${d.getFullYear()}`;

            const option = document.createElement('option');
            option.value = monthValue;
            option.textContent = monthLabel;
            monthSelect.appendChild(option);
        }
    }

    function render() {
        const selectedMonth = monthSelect.value; // YYYY-MM

        // Filter entries for selected month
        const filteredEntries = entries.filter(entry => {
            return entry.date.startsWith(selectedMonth);
        });
        // Already sorted by query, but local filtering applies

        // Calculate stats
        const totalMeals = filteredEntries.length;
        const totalCost = filteredEntries.reduce((sum, entry) => sum + entry.price, 0);
        const uniqueDays = new Set(filteredEntries.map(e => e.date)).size;

        // Update Stats UI
        totalDaysEl.textContent = uniqueDays;
        totalMealsEl.textContent = totalMeals;
        totalCostEl.textContent = `₹${totalCost}`;

        // Render History
        historyList.innerHTML = '';

        if (filteredEntries.length === 0) {
            historyList.innerHTML = '<div class="empty-state">No entries for this month</div>';
            return;
        }

        filteredEntries.forEach(entry => {
            const dateObj = new Date(entry.date);
            const dateStr = dateObj.toLocaleDateString('en-US', { day: 'numeric', month: 'short', weekday: 'short' });
            const typeLabel = entry.mealType === 'veg' ? 'Veg' : 'Non-Veg';
            const timeLabel = entry.mealTime.charAt(0).toUpperCase() + entry.mealTime.slice(1);

            const el = document.createElement('div');
            el.className = 'entry-card';
            el.innerHTML = `
                <div class="entry-info">
                    <span class="entry-date">${dateStr}</span>
                    <span class="entry-details">${timeLabel} • ${typeLabel}</span>
                </div>
                <div class="entry-actions">
                    <span class="entry-price">₹${entry.price}</span>
                    <button class="delete-btn" data-id="${entry.id}">×</button>
                </div>
            `;
            historyList.appendChild(el);
        });

        // Re-attach delete listeners
        document.querySelectorAll('.delete-btn').forEach(btn => {
            btn.addEventListener('click', (e) => {
                const id = e.target.dataset.id;
                deleteEntry(id);
            });
        });
    }
});
